import { TrainTimetable } from "../timetableTypes";

function TimetableStartPage({ timetable }: {timetable: TrainTimetable }) {
  return (
    <html lang="en" style={{ width: "595px", height: "842px", margin: 0 }}>
      <head>
        <meta charSet="utf-8" />
        <title>{`${timetable.trainNoLocal} - Page 1`}</title>
      </head>
      <body style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>

        <a href="./2.html"><button>Next page</button></a>

        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", height: "842px", width: "595px", borderLeft: "2px solid black", borderRight: "2px solid black", justifyContent: "space-between"}}>
          <hr style={{width: "100%", color: "black", background: "black", height: "2px", marginTop: "0px"}}/>

          <div style={{ textAlign: "center" }}>
            <h2>SimRail Linie Kolejowe</h2>
            <h2>Rail Traffic Management Center</h2>
            <h2>in Katowice</h2>
          </div>

          <hr style={{width: "100%", color: "black", background: "black", height: "2px"}}/>

          <div style={{display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "space-between", flexGrow: 1}}>
            <div style={{ textAlign: "center", margin: "50px" }}>
              <h1>Timetable</h1>
              <h1>For train {timetable.trainNoLocal}</h1>
            </div>

            <div style={{ textAlign: "center", margin: "50px" }}>
              <h3>Generated by</h3>
              <h3>Simrail Community Tools</h3>
            </div>
          </div>

          <hr style={{width: "100%", color: "black", background: "black", height: "2px"}}/>

          <div style={{ textAlign: "center" }}>
            <h3>Remember to respect speed limits.</h3>
            <h3>Do not be afraid of delay.</h3>
            <h3>Safety comes first.</h3>
          </div>

          <hr style={{width: "100%", color: "black", background: "black", height: "2px", marginBottom: "0px"}}/>
        </div>

      </body>
    </html>
  );
}

export { TimetableStartPage }