import { TrainTimetable } from "../timetableTypes";

function TimetablePage({ timetable, pageNumber }: {timetable: TrainTimetable, pageNumber: number }) {
  const lastPageRelativeURL = `./${pageNumber-1}.html`
  const nextPageRelativeURL = `./${pageNumber+1}.html`

  var trainNoInternationalString = "";
  if (timetable.trainNoInternational)
    trainNoInternationalString = `(${timetable.trainNoInternational})`

  return (
    <html lang="en" style={{ width: "595px", height: "842px", margin: 0 }}>
      <head>
        <meta charSet="utf-8" />
        <title>{`${timetable.trainNoLocal} - Page ${pageNumber}`}</title>
      </head>
      <body style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>

        <div style={{ alignItems: "end" }}>
          <a href={lastPageRelativeURL}><button>Last page</button></a>
          <a href={nextPageRelativeURL}><button>Next page</button></a>
        </div>

        <div style={{ display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", width: "595px" }}>
          <h5 style={{ margin: 0 }}>{timetable.trainName} {timetable.trainNoLocal} {trainNoInternationalString} Route {timetable.startStation} - {timetable.endStation}</h5>
          <h5 style={{ margin: 0 }}>{pageNumber}</h5>
        </div> 

        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", height: "842px", width: "595px", borderLeft: "1px solid black", borderRight: "1px solid black", justifyContent: "space-between"}}>

          <hr style={{width: "100%", color: "black", background: "black", height: "1px", marginTop: "0px"}}/>

          <div style={{ textAlign: "center" }}>
            <h2>SimRail Linie Kolejowe</h2>
            <h2>Rail Traffic Management Center</h2>
            <h2>in Katowice</h2>
          </div>

          <hr style={{width: "100%", color: "black", background: "black", height: "1px"}}/>

          <div style={{display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "space-between", flexGrow: 1}}>
            <div style={{ textAlign: "center", margin: "50px" }}>
              <h1>Timetable</h1>
              <h1>For train {timetable.trainNoLocal}</h1>
            </div>

            <div style={{ textAlign: "center", margin: "50px" }}>
              <h3>Generated by</h3>
              <h3>Simrail Community Tools</h3>
            </div>
          </div>

          <hr style={{width: "100%", color: "black", background: "black", height: "1px"}}/>

          <div style={{ textAlign: "center" }}>
            <h3>Remember to respect speed limits.</h3>
            <h3>Do not be afraid of delay.</h3>
            <h3>Safety comes first.</h3>
          </div>

          <hr style={{width: "100%", color: "black", background: "black", height: "1px", marginBottom: "0px"}}/>
        </div>

      </body>
    </html>
  );
}

export { TimetablePage };